### PR TITLE
Update WV Primary Screenshot

### PR DESCRIPTION
**Pull request by jesseandersonumd**
Changes tested locally

### CODE REVIEW

**Comment by theomichel** [comment]
Hey @jesseandersonumd, sorry I didn't see this until now. It looks like you used the "URL" field, but that's not implemented yet. @julia326 is doing a big revamp soon, but we're still putting URLs in the spreadsheet for now. (unless I missed a memo, which is possible)

Also, feel free to tag me as a reviewer on PRs.

**Comment by theomichel** [comment]
Huh, I now see that the URL field does seem to work. But I don't understand why it's better to put here rather than in the spreadsheet (for now). Could you explain  @jesseandersonumd ? Thanks!

**Comment by jesseandersonumd** [comment]
> Huh, I now see that the URL field does seem to work. But I don't understand why it's better to put here rather than in the spreadsheet (for now). Could you explain @jesseandersonumd ? Thanks!

Yes! Excellent question. After fiddling around with the page itself, I felt like any of the selectors/divs would be too unreliable and wanted to source from the url of the dashboard directly! We can absolutely put it in the spreadsheet for now while @julia326 revamps. No worries. I wanted to make sure we knew the actual link to the dashboard was there and ideal to source from!

**Comment by theomichel** [comment]
Cool, sourcing from the URL of the dashboard directly seems like the way to go. And yeah I think it would be best to remove the URL from the yaml for now. (and then we can move them all from the spreadsheet in one fell swoop) Thanks!

**Comment by julia326** [comment]
Hi @jesseandersonumd sorry just revisiting this now - is this change still needed?

**Comment by julia326** [comment]
Closing this one out since we moved the code to the screenshots repo, but please reopen there if I'm wrong to close this one! Thank you @jesseandersonumd

**Pull request closed without merging**
