### PR TITLE
Add license section to README

### LINKED ISSUE #18: License the data under a Creative Commons Zero license
Right now this data is being licensed under the Apache license (same as the rest of the COVID19Tracking website). While the Apache license is great for software, it doesn't really make any sense for a data set (for example, there are no patent rights associated with data) and is likely incompatible with other licenses that are used for data, thus limiting people's ability to combine this data with other datasets. I would suggest licensing this specific repo under a Creative Commons license such as CC Attribution, CC0, or CC Attribution-ShareAlike. You could even dual license it under both Apache and a CC license if you wanted to (allowing the reuser to choose one license or the other).

### PR DESCRIPTION
**Pull request by mlinksva**
Just making a concrete version of a suggestion in #18.

Fixes #18

### CODE REVIEW

**Comment by kaldari** [comment]
This looks good to me. What do you think @metasj? We can also add some licensing info to the [API page](https://covidtracking.com/api), but that will need to be done in the website repo.

**Comment by metasj** [comment]
That looks good, thank you Mike :)

**Comment by kevee** [comment]
I updated the proposed change to [incorporate our project-wide license](https://covidtracking.com/license).

**Comment by julia326** [comment]
Our license situation has evolved since this PR - closing as inactive for now, but please feel free to reopen!

**Pull request closed without merging**
