### PR TITLE
Fix Tennessee 4/29 & 4/30

### PR DESCRIPTION
**Pull request by jawiv**
See screenshots from covidtracking logs. It looks like the 4/29 screenshot that usually occurs late night did not happen and the 5pm one did not capture the real 4/29 data. So the first 4/30 screenshot (11:20am) has the 4/29 data. The 11pm 4/30 screenshot has the 4/30 data. I did NOT update the hash or time information, only the data. I have attached all screenshots (linked to covidtracking logs)

4/29 538pm: https://covidtracking.com/screenshots/TN/TN-20200429-062033.png
4/30 1120am: https://covidtracking.com/screenshots/TN/TN-20200430-122007.png
4/30 1120pm: https://covidtracking.com/screenshots/TN/TN-20200501-002008.png

### CODE REVIEW

**Comment by jawiv** [comment]
It looks like Tennessee may have been late to publish data in the 4/28-4/30 range, coupled with fewer daily screenshots being taken may have affected any automation in place to pull this information. Tennessee may also have revised the formatting of their data page, which may have affected any data automation. As noted in the comment, I did not change any date information or the hash of the day's information. Please double check that my calculations are correct. I included links to the screenshots to help assist in the verification. 

Cheers.

**Comment by jawiv** [comment]
Whoops, accidentally closed this

**Comment by muamichali** [comment]
HI @jawiv, 
This repo just saves copies of the data published by the API. If you are finding inaccuracies in the data, please post an issue in the issues repo, and we will investigate and fix it in the underlying data. 

https://github.com/COVID19Tracking/issues

**Comment by jawiv** [comment]
Thanks @muamichali. There already was an issue filed appropriately (which we've both had activity on), so I will go ahead and close this out.

Thanks for the clarity on this repo!

Cheers!

**Pull request closed without merging**
