### PR TITLE
Missing dates for Michigan new positive cases

### PR DESCRIPTION
**Pull request by bradgowland**
Aggregates were correct, but some missing days for Michigan data would add the total of two days of cases:
- 4 new positives on 3/12, 10 new positives on 3/13 instead of 14 new positives on 3/13
- 993 new positives on 3/28, 836 new positives on 3/29 instead of 1,829 new cases on 3/29

### CODE REVIEW

**Comment by Nosferican** [comment]
Was the data updated at the source or just at the backups? Asking on whether the people using the API to query it currently will have the updated or old values.

**Comment by julia326** [comment]
Hi folks, we have a structured process around data updates - the backups in this repo are meant to reflect what we serve from the API. @bradgowland thanks for the MI data sleuthing! I'll pass this on to our data team and they'll evaluate

**Comment by bradgowland** [comment]
@julia326 thanks for passing along! Let me know if there's a better way to propose any corrections in the future. I work with Michigan Radio, Southeastern Michigan's NPR station, we're using the API for some graphics on our site and we follow the Michigan numbers closely.

**Comment by Nosferican** [comment]
One of the projects I maintain relies on looking at the historical backups `data/states.csv` since the API doesn't currently serve the jurisdictions' reporting assessments on an observation basis. I would avoid changing the values in the backups. Currently I crawl every version of the file to build the historical reference files... I validate and check for conflicts but would still be best to keep the data as it was served then.

**Comment by julia326** [comment]
@Nosferican we publish historical daily state-level data also, at https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_daily_4pm_et.csv - would that serve your needs or is there another way you're constructing the history?

**Comment by Nosferican** [comment]
I use that endpoint for the daily statistics, but use the historical records to attach the `grade` from the `data/states.csv` at the time of the report. The REST API only reports the latest data not the historical and the GraphQL hasn't implemented the reporting quality checks. Here is the [reference](https://github.com/uva-bi-sdad/COVID_Tracking_Clean). The resulting data looks like [this](https://github.com/uva-bi-sdad/COVID_Tracking_Clean/blob/master/data/daily.tsv).

**Comment by muamichali** [comment]
Hi @bradgowland,
I am sorry it took so long to get to this working on this issue over at our issues repo. https://github.com/COVID19Tracking/issues/issues/111 Do you happen to have the total positives for the dates that need correction? And would you happen to have the sources for the data? Thanks so much

**Comment by julia326** [comment]
Closing for now as this seems inactive, but please feel free to reopen!

**Pull request closed without merging**
