### PR TITLE
Change Secondary Screenshot Message for OK

### PR DESCRIPTION
**Pull request by jesseandersonumd**
Tested locally

### CODE REVIEW

**Comment by theomichel** [comment]
hey @jesseandersonumd, the only change I see in this PR is the addition of "hi" at the end of the message. Let me know if I can help with github wrangling... I know it can be a pain!

**Comment by jesseandersonumd** [comment]
Hi, Theo! 

We made this as a test example to help Hannah and Daniel go through the process of actually proposing changes on Github! Feel free to delete this :)

**Comment by theomichel** [comment]
I don't know how 😬. Maybe if I click the "close with comment" button. Let's see what happens!

**Comment by theomichel** [comment]
It worked!

**Pull request closed without merging**
